// Isolated Electron renderer checks. No production profile, network, or updater.
const { app, BrowserWindow, ipcMain, session } = require('electron');
const fs = require('fs');
const path = require('path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const output = path.join(root, 'dist', 'beta-ui-check');
fs.mkdirSync(output, { recursive: true });
for (const name of ['failure.txt', 'result.json']) fs.rmSync(path.join(output, name), { force: true });
app.setPath('userData', path.join(output, 'profile'));
if (process.env.BETA_UI_SOFTWARE_RENDERING === '1') app.disableHardwareAcceleration();
app.commandLine.appendSwitch('disable-gpu-shader-disk-cache');
const errors = [];
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
app.whenReady().then(async () => {
  app.on('session-created', ses => ses.webRequest.onBeforeRequest({ urls: ['http://*/*', 'https://*/*'] }, (_, cb) => cb({ cancel: true })));
  session.defaultSession.webRequest.onBeforeRequest({ urls: ['http://*/*', 'https://*/*'] }, (_, cb) => cb({ cancel: true }));
  await session.defaultSession.clearStorageData();
  const responses = { 'get-downloads': [], 'get-permissions': {}, 'get-download-path': 'Downloads', 'get-float-ball-enabled': true, 'get-app-version': require('../package.json').version, 'window-is-maximized': false };
  const preload = fs.readFileSync(path.join(root, 'preload.js'), 'utf8');
  for (const match of preload.matchAll(/ipcRenderer\.invoke\('([^']+)'/g)) ipcMain.handle(match[1], () => responses[match[1]] ?? true);
  const win = new BrowserWindow({ width: 1280, height: 820, show: false, frame: false, webPreferences: { preload: path.join(root, 'preload.js'), contextIsolation: true, nodeIntegration: false, webviewTag: true, backgroundThrottling: false } });
  win.webContents.on('console-message', (_event, details) => {
    if (details.level === 'error' && !/ERR_BLOCKED_BY_CLIENT|Failed to load resource/.test(details.message)) errors.push(details.message);
  });
  const js = code => win.webContents.executeJavaScript(code, true);
  const click = selector => js(`document.querySelector(${JSON.stringify(selector)}).click()`);
  const shot = async name => { await delay(300); fs.writeFileSync(path.join(output, name + '.png'), (await win.webContents.capturePage()).toPNG()); };
  await win.loadFile(path.join(root, 'index.html'));
  win.showInactive();
  await delay(700);
  assert.equal(await js(`document.querySelectorAll('.tab-item').length`), 9);
  assert.equal(await js(`getComputedStyle(document.querySelector('#sidebar')).backdropFilter.includes('blur')`), true);
  await click('#new-tab-btn');
  await delay(700);
  assert.equal(await js(`document.querySelectorAll('.top-tab').length`), 2);
  await shot('light');
  await click('#settings-btn');
  await shot('settings-light');
  await click('[data-theme="dark"]');
  assert.equal(await js(`localStorage.getItem('aihub-theme')`), 'dark');
  await shot('settings-dark');
  assert.equal(await js(`document.querySelector('webview.visible').executeJavaScript("document.body.classList.contains('dark')")`), true);
  await click('[data-panel="sites"]');
  assert.equal(await js(`document.querySelectorAll('.site-manage-row').length`), 9);
  await shot('sites-dark');
  await click('#settings-close');
  await click('#dl-btn');
  await shot('downloads-dark');
  assert.equal(await js(`document.querySelector('#download-panel').classList.contains('show')`), true);
  assert.equal(await js(`getComputedStyle(document.querySelector('#download-panel')).visibility`), 'visible');
  await click('#dl-btn');
  await click('#add-site-btn');
  await js(`document.querySelector('#site-name-input').value = 'Example'; document.querySelector('#site-url-input').value = 'https://example.com';`);
  await click('#site-form-submit');
  assert.equal(await js(`document.querySelectorAll('.tab-item').length`), 10);
  await click('#collapse-btn');
  await delay(300);
  assert.equal(await js(`Math.round(document.querySelector('#sidebar').getBoundingClientRect().width)`), 64);
  await shot('collapsed-dark');
  win.setSize(480, 640);
  await click('#settings-btn');
  await click('[data-panel="appearance"]');
  await shot('settings-narrow');
  assert.equal(await js(`document.querySelector('#settings-dialog').getBoundingClientRect().right <= innerWidth`), true);
  assert.equal(await js(`document.querySelector('#settings-panels').scrollWidth <= document.querySelector('#settings-panels').clientWidth`), true);
  await click('#settings-close');
  await js(`location.reload()`);
  await delay(700);
  assert.equal(await js(`document.body.classList.contains('dark') && document.querySelector('#sidebar').classList.contains('collapsed')`), true);
  assert.equal(await js(`document.querySelectorAll('.tab-item').length`), 10);
  await win.webContents.debugger.attach('1.3');
  await win.webContents.debugger.sendCommand('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] });
  assert.equal(await js(`getComputedStyle(document.querySelector('#sidebar')).transitionDuration`), '0s');
  win.webContents.debugger.detach();
  win.setSize(1280, 820);
  await win.loadFile(path.join(root, 'newtab.html'), { query: { theme: 'dark' } });
  await shot('newtab-dark');
  for (const [query, expected] of [['example.com', 'https://example.com/'], ['毛玻璃设计', 'https://www.baidu.com/s?wd=' + encodeURIComponent('毛玻璃设计')]]) {
    await win.loadFile(path.join(root, 'newtab.html'));
    const navigation = new Promise(resolve => win.webContents.once('will-navigate', (event, url) => { event.preventDefault(); resolve(url); }));
    await js(`document.querySelector('#q').value = ${JSON.stringify(query)}; document.querySelector('#search-form').requestSubmit()`);
    assert.equal(await navigation, expected);
  }
  const floatWin = new BrowserWindow({ width: 120, height: 120, frame: false, transparent: true, show: false, webPreferences: { preload: path.join(root, 'floatball-preload.js'), contextIsolation: true, nodeIntegration: false } });
  await floatWin.loadFile(path.join(root, 'floatball.html'));
  floatWin.showInactive();
  const floatJs = code => floatWin.webContents.executeJavaScript(code);
  assert.equal(await floatJs(`getComputedStyle(document.querySelector('.float-launcher')).backgroundImage`), 'none');
  assert.equal(await floatJs(`getComputedStyle(document.querySelector('.float-launcher')).borderRadius`), '14px');
  floatWin.webContents.send('float-ball-accent-change', '#786c60');
  await delay(300);
  assert.equal(await floatJs(`document.querySelector('.float-launcher').style.getPropertyValue('--float-color')`), '#786c60');
  fs.writeFileSync(path.join(output, 'float.png'), (await floatWin.webContents.capturePage()).toPNG());
  floatWin.destroy();
  assert.deepEqual(errors, []);
  fs.writeFileSync(path.join(output, 'result.json'), JSON.stringify({ passed: true, checks: ['renderer startup', 'glass styles', 'new tab and live theme sync', 'light/dark settings', 'site management', 'add site', 'downloads', 'collapse', '480px layout', 'persistence', 'reduced motion', 'search and URL navigation', 'float appearance and accent IPC', 'no renderer errors'], screenshots: output }, null, 2));
  console.log('Beta UI checks passed: ' + output);
  win.destroy();
  app.quit();
}).catch(error => { console.error(error); fs.writeFileSync(path.join(output, 'failure.txt'), String(error.stack)); app.exit(1); });
